### ISSUE TITLE
premium contain not able to play

### ISSUE THREAD

**Issue by Gujjugaming2k** [KapilYadav-dev/Zeepium#7]
premium contain not able to play
like https://www.zee5.com/movies/details/radhe-your-most-wanted-bhai/0-0-399328

**Comment by KapilYadav-dev** [comment]
We don't support Salman khan movies.😂
I'll look into this issue, if you want to contribute then do let me know.

**Comment by Gujjugaming2k** [comment]
Lol, i just that because of drm play that why

**Comment by KapilYadav-dev** [comment]
Sure, I'll look into the matter :)
Happy scrapping
